name: Secure Deploy to S3 + CloudFront

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS with OIDC (No Keys!)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::361960318571:role/GitHub-bzlink-deploy-role
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync . s3://YOUR-BUCKET-NAME --delete --exclude ".git/*" --exclude ".github/*"

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
